const universityList = [
    {"value": 1, "label": "University of Dhaka"},
    {"value": 2, "label": "University of Rajshahi"},
    {"value": 3, "label": "Bangladesh Agricultural University"},
    {"value": 4, "label": "Bangladesh University of Engineering & Technology"},
    {"value": 5, "label": "University of Chittagong"},
    {"value": 6, "label": "Jahangirnagar University"},
    {"value": 7, "label": "Islamic University, Bangladesh"},
    {"value": 8, "label": "Shahjalal University of Science & Technology"},
    {"value": 9, "label": "Khulna University"},
    {"value": 10, "label": "National University"},
    {"value": 11, "label": "Bangladesh Open University"},
    {"value": 12, "label": "Bangabandhu Sheikh Mujib Medical University"},
    {"value": 13, "label": "Bangabandhu Sheikh Mujibur Rahman Agricultural University"},
    {"value": 14, "label": "Hajee Mohammad Danesh Science & Technology University"},
    {"value": 15, "label": "Mawlana Bhashani Science & Technology University"},
    {"value": 16, "label": "Patuakhali Science And Technology University"},
    {"value": 17, "label": "Sher-e-Bangla Agricultural University"},
    {"value": 18, "label": "Chittagong University of Engineering & Technology"},
    {"value": 19, "label": "Rajshahi University of Engineering & Technology"},
    {"value": 20, "label": "Khulna University of Engineering & Technology"},
    {"value": 21, "label": "Dhaka University of Engineering & Technology"},
    {"value": 22, "label": "Noakhali Science & Technology University"},
    {"value": 23, "label": "Jagannath University"},
    {"value": 24, "label": "Comilla University"},
    {"value": 25, "label": "Jatiya Kabi Kazi Nazrul Islam University"},
    {"value": 26, "label": "Chittagong Veterinary and Animal Sciences University"},
    {"value": 27, "label": "Sylhet Agricultural University"},
    {"value": 28, "label": "Jessore University of Science & Technology"},
    {"value": 29, "label": "Pabna University of Science and Technology"},
    {"value": 30, "label": "Begum Rokeya University, Rangpur"},
    {"value": 31, "label": "Bangladesh University of Professionals"},
    {"value": 32, "label": "Bangabandhu Sheikh Mujibur Rahman Science & Technology University"},
    {"value": 33, "label": "Bangladesh University of Textiles"},
    {"value": 34, "label": "University of Barishal"},
    {"value": 35, "label": "Rangamati Science and Technology University"},
    {"value": 36, "label": "Bangabandhu Sheikh Mujibur Rahman Maritime University, Bangladesh"},
    {"value": 37, "label": "Islamic Arabic University"},
    {"value": 38, "label": "Chittagong Medical University"},
    {"value": 39, "label": "Rajshahi Medical University"},
    {"value": 40, "label": "Rabindra University, Bangladesh"},
    {"value": 41, "label": "Bangabandhu Sheikh Mujibur Rahman Digital University, Bangladesh"},
    {"value": 42, "label": "Sheikh Hasina University"},
    {"value": 43, "label": "Khulna Agricultural University"},
    {"value": 44, "label": "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University"},
    {"value": 45, "label": "Bangamata Sheikh Fazilatunessa Mujib Medical University, Sylhet"},
    {"value": 46, "label": "Bangabandhu Sheikh Mujibur Rahman Aviation And Aerospace University (BSMRAAU)"},
    {"value": 47, "label": "Chandpur Science and Technology University"},
    {"value": 48, "label": "Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj"},
    {"value": 49, "label": "Hobiganj Agricultural University"},
    {"value": 50, "label": "Sheikh Hasina Medical University, Khulna"},
    {"value": 51, "label": "Kurigram Agricultural University"},
    {"value": 52, "label": "Sunamganj Science and Technology University"},
    {"value": 53, "label": "Bangabandhu Sheikh Mujibur Rahman Science & Technology University, Pirojpur"},
    {"value": 54, "label": "Bangabandhu Sheikh Mujibur Rahman University, Naogaon"},
    {"value": 55, "label": "Mujibnagar University, Meherpur"},
    {"value": 56, "label": "Islamic University of Technology, Gazipur"},
    {"value": 57, "label": "Asian University for Women"},
    {"value": 58, "label": "South Asian University"},
    {"value": 59, "label": "North South University"},
    {"value": 60, "label": "University of Science & Technology Chittagong"},
    {"value": 61, "label": "Independent University, Bangladesh"},
    {"value": 62, "label": "Central Women's University"},
    {"value": 63, "label": "International University of Business Agriculture & Technology"},
    {"value": 64, "label": "International Islamic University Chittagong"},
    {"value": 65, "label": "Ahsanullah University of Science and Technology"},
    {"value": 66, "label": "American International University-Bangladesh"},
    {"value": 67, "label": "East West University"},
    {"value": 68, "label": "University of Asia Pacific"},
    {"value": 69, "label": "Gono Bishwabidyalay"},
    {"value": 70, "label": "The People's University of Bangladesh *"},
    {"value": 71, "label": "Asian University of Bangladesh"},
    {"value": 72, "label": "Dhaka International University"},
    {"value": 73, "label": "Manarat International University"},
    {"value": 74, "label": "BRAC University"},
    {"value": 75, "label": "Bangladesh University *"},
    {"value": 76, "label": "Leading University"},
    {"value": 77, "label": "BGC Trust University Bangladesh"},
    {"value": 78, "label": "Sylhet International University"},
    {"value": 79, "label": "University of Development Alternative"},
    {"value": 80, "label": "Premier University"},
    {"value": 81, "label": "Southeast University"},
    {"value": 82, "label": "Daffodil International University"},
    {"value": 83, "label": "Stamford University Bangladesh"},
    {"value": 84, "label": "State University of Bangladesh (SUB)"},
    {"value": 85, "label": "City University"},
    {"value": 86, "label": "Prime University"},
    {"value": 87, "label": "Northern University Bangladesh"},
    {"value": 88, "label": "Southern University Bangladesh"},
    {"value": 89, "label": "Green University of Bangladesh"},
    {"value": 90, "label": "Pundra University of Science & Technology"},
    {"value": 91, "label": "World University of Bangladesh"},
    {"value": 92, "label": "Shanto-Mariam University of Creative Technology"},
    {"value": 93, "label": "The Millennium University"},
    {"value": 94, "label": "Eastern University"},
    {"value": 95, "label": "Metropolitan University"},
    {"value": 96, "label": "Uttara University"},
    {"value": 97, "label": "United International University"},
    {"value": 98, "label": "University of South Asia"},
    {"value": 99, "label": "Victoria University of Bangladesh *"},
    {"value": 100, "label": "Bangladesh University of Business & Technology"},
    {"value": 101, "label": "Presidency University"},
    {"value": 102, "label": "University of Information Technology & Sciences"},
    {"value": 103, "label": "Primeasia University"},
    {"value": 104, "label": "Royal University of Dhaka"},
    {"value": 105, "label": "University of Liberal Arts Bangladesh"},
    {"value": 106, "label": "Atish Dipankar University of Science & Technology"},
    {"value": 107, "label": "Bangladesh Islami University"},
    {"value": 108, "label": "ASA University Bangladesh"},
    {"value": 109, "label": "East Delta University"},
    {"value": 110, "label": "European University of Bangladesh *"},
    {"value": 111, "label": "Varendra University"},
    {"value": 112, "label": "Hamdard University Bangladesh"},
    {"value": 113, "label": "BGMEA University of Fashion & Technology(BUFT) (2)"},
    {"value": 114, "label": "North East University Bangladesh"},
    {"value": 115, "label": "First Capital University of Bangladesh"},
    {"value": 116, "label": "Ishakha International University, Bangladesh"},
    {"value": 117, "label": "Z.H Sikder University of Science & Technology"},
    {"value": 118, "label": "Exim Bank Agricultural University, Bangladesh"},
    {"value": 119, "label": "North Western University"},
    {"value": 120, "label": "Khwaja Yunus Ali University"},
    {"value": 121, "label": "Sonargaon University"},
    {"value": 122, "label": "Feni University"},
    {"value": 123, "label": "Britannia University"},
    {"value": 124, "label": "Port City International University"},
    {"value": 125, "label": "Bangladesh University of Health Sciences"},
    {"value": 126, "label": "Chittagong Independent University"},
    {"value": 127, "label": "Notre Dame University Bangladesh"},
    {"value": 128, "label": "Times University, Bangladesh"},
    {"value": 129, "label": "North Bengal International University"},
    {"value": 130, "label": "Fareast International University"},
    {"value": 131, "label": "Rajshahi Science & Technology University (RSTU), Natore"},
    {"value": 132, "label": "Sheikh Fazilatunnesa Mujib University"},
    {"value": 133, "label": "Cox's Bazar International University"},
    {"value": 134, "label": "R. P. Shaha University"},
    {"value": 135, "label": "German University Bangladesh"},
    {"value": 136, "label": "Global University Bangladesh"},
    {"value": 137, "label": "CCN University of Science & Technology"},
    {"value": 138, "label": "Bangladesh Army University of Science and Technology(BAUST), Saidpur"},
    {"value": 139, "label": "Bangladesh Army University of Engineering and Technology (BAUET), Qadirabad"},
    {"value": 140, "label": "Bangladesh Army International University of Science & Technology(BAIUST) ,Comilla"},
    {"value": 141, "label": "University of Scholars"},
    {"value": 142, "label": "Canadian University of Bangladesh"},
    {"value": 143, "label": "N.P.I University of Bangladesh"},
    {"value": 144, "label": "Northern University of Business & Technology, Khulna"},
    {"value": 145, "label": "Rabindra Maitree University, Kushtia"},
    {"value": 146, "label": "University of Creative Technology, Chittagong"},
    {"value": 147, "label": "Central University of Science and Technology **"},
    {"value": 148, "label": "Tagore University of Creative Arts, Uttara, Dhaka, Bangladesh"},
    {"value": 149, "label": "University of Global Village"},
    {"value": 150, "label": "Rupayan A.K.M Shamsuzzoha University"},
    {"value": 151, "label": "Anwer Khan Modern University"},
    {"value": 152, "label": "ZNRF University of Management Sciences"},
    {"value": 153, "label": "Ahsania Mission University of Science and Technology"},
    {"value": 154, "label": "Khulna Khan Bahadur Ahsanullah University"},
    {"value": 155, "label": "Bandarban University"},
    {"value": 156, "label": "Shah Makhdum Management University, Rajshahi"},
    {"value": 157, "label": "Trust University, Barishal"},
    {"value": 158, "label": "International Standard University"},
    {"value": 159, "label": "University of Brahmanbaria"},
    {"value": 160, "label": "University of Skill Enrichment and Technology"},
    {"value": 161, "label": "Microland University of Science and Technology"},
    {"value": 162, "label": "R.T.M Al-Kabir Technical University"},
    {"value": 163, "label": "Sheikh Hasina University of Science and Technology"},
    {"value": 164, "label": "Chattogram BGMEA University of Fashion and Technology"},
    {"value": 165, "label": "Bangladesh Army University of Science and Technology, Khulna"},
    {"value": 166, "label": "Teesta University, Rangpur"},
    {"value": 167, "label": "International Islami University of Science and Technology"},
    {"value": 168, "label": "Lalon University of Science and Arts"},
    {"value": 169, "label": "IBAIS University ***"},
    {"value": 170, "label": "The University of Comilla ***"},
    {"value": 171, "label": "Queens University **"},
    {"value": 172, "label": "America Bangladesh University ***"}
]





export default universityList;
